package de.htwg.se.dicewars.state;

/**
 * Stati for Controller and View
 */
public enum Status {

	VALIDATTACK , 
	INVALIDATTACKNEIGHBOR , 
	INVALIDATTACKDICES , 
	INVALIDATTACKOWNER , 
	INVALIDATTACKFIELD , 
	ATTACKSUCCESS , 
	ATTACKFAILED , 
	NEW,
	PLAYERUPDATE ,
	NOTHINGTOUPDATE ,
	INTERRUPTROUTINE ,
	DICEERROR ,
	PLAYERSTURNERROR ,
	INVALIDOWNER ,
	SUCCESS ,
	FAILED ,
	ENDTURN ,
	VALID ,
	CHOOSEAKTION ,

}
